title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false #false if you don't want downloads or true if you want
google_analytics:
theme: jekyll-theme-cayman